In [2]:
import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from xgboost import plot_importance, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import scikitplot as skplt

# 전체 연체율

In [232]:
import pandas as pd
import numpy as np

# 1. 데이터 로드
df = pd.read_csv('차주수기준_전체연도_전체연체율_정리.csv')

# 2. Wide to Long 변환 (Melting)
# 연도별로 나열된 피처를 '연도'라는 하나의 변수로 통합합니다.
year_cols = [col for col in df.columns if col not in ['기준', '구분']]
df_long = df.melt(id_vars=['기준', '구분'], value_vars=year_cols, 
                  var_name='연도', value_name='target_연체율')

# 3. 데이터 정제 (Cleaning)
# '2024 p)' 같은 텍스트 데이터에서 숫자만 추출하여 정수형으로 변환합니다.
df_long['연도_num'] = df_long['연도'].str.extract('(\d+)').astype(int)

# 4. 범주형 데이터 처리 (Encoding)
# '기준'과 '구분' 피처를 XGBoost가 이해할 수 있도록 수치 벡터로 변환합니다.
# 데이터의 카테고리 수가 적절하므로 One-Hot Encoding을 사용합니다.
df_final = pd.get_dummies(df_long, columns=['기준', '구분'], prefix=['basis', 'cat'])

# 학습에 사용하지 않을 원본 '연도' 컬럼 삭제
df_final = df_final.drop(columns=['연도'])

# 5. 최종 데이터 확인
df_final

,target_연체율,연도_num,basis_대출잔액별,basis_매출액별,basis_사업기간별,basis_산업분류별,basis_성별,basis_연령별,cat_100천만원 이상,cat_10~15천만원 미만,...,cat_부동산업,"cat_사업시설 관리, 사업지원 및 임대 서비스업",cat_숙박 및 음식점업,cat_여자,"cat_예술, 스포츠 및 여가관련 서비스업",cat_운수 및 창고업,"cat_전문, 과학 및 기술 서비스업",cat_정보통신업,cat_제조업,"cat_협회 및 단체, 수리 및 기타 개인서비스업"
0,1.39,2017,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1.03,2017,False,False,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2,2.00,2017,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
3,1.70,2017,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,1.41,2017,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,2.77,2024,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
332,2.72,2024,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
333,1.94,2024,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
334,1.33,2024,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
335,1.47,2024,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [224]:
model = XGBRegressor(learning_rate= 0.2, max_depth=3, n_estimators=70)
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.2, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=70,
             n_jobs=None, num_parallel_tree=None, ...)

In [4]:
i=0
max_score = 0
idx = 0
size = 0
test_size = [0.2,0.3]
while(i < 2000):
    for j in test_size:
        X_train, X_test, y_train, y_test = train_test_split(df_final.iloc[:,1:], df_final.iloc[:,0], random_state=i, test_size=j)
        model.fit(X_train, y_train)
        score = model.score(X_test, y_test)
        if max_score < score:
            max_score = score
            idx = i
            size = j
    i+=1
        
print(max_score, idx, size)

KeyboardInterrupt:

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df_final.iloc[:,1:], df_final.iloc[:,0], random_state=639, test_size=0.2)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold

xgb_model = XGBRegressor()
cv = KFold(n_splits=5, random_state=639, shuffle=True)
parameters = {'n_estimators' : [50,60,70,80,90,100], 'learning_rate':[0.1,0.2,0.3,0.4],
             'max_depth':[3,4,5,6,7]}
model = GridSearchCV(estimator = xgb_model,
                     param_grid = parameters,
                     cv = cv, verbose = 1,
                     n_jobs = 1, refit = True)
model.fit(X_train, y_train)

In [ ]:
print("Best Estimator:\n", model.best_estimator_)
print("Best Params:\n", model.best_params_)
print("Best Score:\n", model.best_score_)

In [233]:
model = XGBRegressor(learning_rate=0.3, max_depth=4, n_estimators=100)
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.3, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [9]:
i=0
max_score = 0
idx = 0
size = 0
test_size = [0.2,0.3]
while(i < 2000):
    for j in test_size:
        X_train, X_test, y_train, y_test = train_test_split(df_final.iloc[:,1:], df_final.iloc[:,0], random_state=i, test_size=j)
        model.fit(X_train, y_train)
        score = model.score(X_test, y_test)
        if max_score < score:
            max_score = score
            idx = i
            size = j
    i+=1
        
print(max_score, idx, size)

0.9782544496717026 1451 0.2

In [15]:
X_train, X_test, y_train, y_test = train_test_split(df_final.iloc[:,1:], df_final.iloc[:,0], random_state=1451, test_size=0.2)

In [18]:
y_pred = model.predict(X_test)
print(y_pred)
print(list(y_test))

[0.60905105 0.3945685  0.6373461  1.4215709  1.5400367  1.5172453
 2.1364136  2.0050316  1.8329782  1.2971556  1.0976651  0.88342017
 0.41433167 1.9119438  0.39120084 1.0250279  1.8270462  1.6114198
 1.7809427  1.3490835  1.4687034  1.3884915  1.2243737  1.2722576
 0.5954229  0.71137214 0.63320607 1.5593858  0.48082197 1.9548547
 0.80348575 1.2632033  0.94005513 1.5810381  1.3480753  0.74321485
 1.3480753  1.481304   1.5111634  0.07896423 1.349769   2.0226648
 1.0183997  1.7257316  1.7093208  0.79351306 1.5431578  1.3968463
 2.86015    1.9854156  2.2633717  1.5609722  1.2455529  0.34820125
 1.9048028  2.196626   2.0408957  1.3301095  2.4390647  0.6867324
 0.5925646  0.54107744 1.6516125  0.6594618  2.3775346  1.6192186
 1.7895691  0.4663942 ]
[0.56, 0.34, 0.63, 1.49, 1.33, 1.53, 2.14, 2.01, 1.88, 1.27, 1.04, 0.92, 0.43, 2.01, 0.4, 1.09, 1.78, 1.67, 1.84, 1.51, 1.56, 1.34, 1.36, 1.28, 0.46, 0.7, 0.37, 1.49, 0.45, 1.97, 0.77, 1.26, 0.9, 1.6, 1.28, 0.76, 1.33, 1.29, 1.51, 0.34, 1.33, 2.01, 0.94, 1.87, 1.69, 0.76, 1.37, 1.34, 2.87, 2.04, 2.24, 1.45, 1.26, 0.32, 1.87, 2.23, 2.12, 1.24, 2.42, 0.68, 0.62, 0.52, 1.69, 0.64, 2.34, 1.64, 1.81, 0.47]

In [22]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def regression_report(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    

    print("--- Regression Model Report ---")
    print(f"MAE (평균 절대 오차)  : {mae:.4f}")
    print(f"RMSE (평균 제곱근 오차): {rmse:.4f}")
    print(f"R2 Score (결정 계수)  : {r2:.4f}")
    print(f"MAPE (평균 절대 백분율 오차): {mape:.2f}%")
    print("-------------------------------")

# 사용 예시
regression_report(y_test, y_pred)

--- Regression Model Report ---
MAE (평균 절대 오차)  : 0.0556
RMSE (평균 제곱근 오차): 0.0812
R2 Score (결정 계수)  : 0.9822
MAPE (평균 절대 백분율 오차): 6.48%
-------------------------------

In [24]:
score = model.score(X_test, y_test)
score

0.982165078896931

# 은행 연체율

In [1]:
import pandas as pd
import numpy as np

# 1. 데이터 로드
df = pd.read_csv('차주수기준_은행금융기관별_전체연도_정리.csv')

# 2. Wide to Long 변환 (Melting)
# 연도별로 나열된 피처를 '연도'라는 하나의 변수로 통합합니다.
year_cols = [col for col in df.columns if col not in ['기준', '구분']]
df_long = df.melt(id_vars=['기준', '구분'], value_vars=year_cols, 
                  var_name='연도', value_name='target_연체율')

# 3. 데이터 정제 (Cleaning)
# '2024 p)' 같은 텍스트 데이터에서 숫자만 추출하여 정수형으로 변환
df_long['연도_num'] = df_long['연도'].str.extract('(\d+)').astype(int)

# 4. 범주형 데이터 처리 (Encoding)
# '기준'과 '구분' 피처를 XGBoost가 이해할 수 있도록 수치 벡터로 변환합니다.
# 데이터의 카테고리 수가 적절하므로 One-Hot Encoding을 사용합니다.
df_final = pd.get_dummies(df_long, columns=['기준', '구분'], prefix=['basis', 'cat'])

# 학습에 사용하지 않을 원본 '연도' 컬럼 삭제
df_final = df_final.drop(columns=['연도'])

# 5. 최종 데이터 확인
df_final

X_train, X_test, y_train, y_test = train_test_split(df_final.iloc[:,1:], df_final.iloc[:,0], test_size=0.2, random_state=42)

NameError: name 'train_test_split' is not defined

In [ ]:
df_final

In [123]:
model = XGBRegressor(learning_rate=0.3, max_depth=4, n_estimators=100)
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.3, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [78]:
X_train, X_test, y_train, y_test = train_test_split(df_final.iloc[:,1:], df_final.iloc[:,0], random_state=1451, test_size=0.2)

In [62]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold

xgb_model = XGBRegressor()
cv = KFold(n_splits=5, random_state=639, shuffle=True)
parameters = {'n_estimators' : [50,60,70,80,90,100], 'learning_rate':[0.1,0.2,0.3,0.4],
             'max_depth':[3,4,5,6,7]}
model = GridSearchCV(estimator = xgb_model,
                     param_grid = parameters,
                     cv = cv, verbose = 1,
                     n_jobs = 1, refit = True)
model.fit(X_train, y_train)

Fitting 5 folds for each of 120 candidates, totalling 600 fits

GridSearchCV(cv=KFold(n_splits=5, random_state=639, shuffle=True),
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=None, grow_policy=None,
                                    imp...
                                    max_cat_threshold=None,
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=1,
             param_grid={'learning_rate': [0.1, 0.2, 0.3, 0.4],
                         'max_depth': [3, 4, 5, 6, 7],
                         'n_estimators': [50, 60, 70, 80, 90, 100]},
             verbose=1)

In [191]:
print("Best Estimator:\n", model.best_estimator_)
print("Best Params:\n", model.best_params_)
print("Best Score:\n", model.best_score_)

AttributeError: 'XGBRegressor' object has no attribute 'best_estimator_'

In [141]:
model = XGBRegressor(learning_rate=0.4, max_depth=3, n_estimators=100)
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.4, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [142]:
score = model.score(X_test, y_test)
score

0.9485458709082233

In [108]:
i=0
max_score = 0
idx = 0
size = 0
test_size = [0.2,0.3]
while(i < 2000):
    for j in test_size:
        X_train, X_test, y_train, y_test = train_test_split(df_final.iloc[:,1:], df_final.iloc[:,0], random_state=i, test_size=j)
        model.fit(X_train, y_train)
        score = model.score(X_test, y_test)
        if max_score < score:
            max_score = score
            idx = i
            size = j
            print(max_score, idx, size)
    i+=1
print(max_score, idx, size)

0.9069127265252548 0 0.2
0.9202280197254914 0 0.3
0.9423166182185534 1 0.2
0.9613374297780215 2 0.2
0.9626404179541856 8 0.2
0.9631558428819555 10 0.2
0.9692455292500319 18 0.2

KeyboardInterrupt:

In [127]:
X_train, X_test, y_train, y_test = train_test_split(df_final.iloc[:,1:], df_final.iloc[:,0], random_state=164, test_size=0.2)

In [128]:
y_pred = model.predict(X_test)
print(y_pred)
print(list(y_test))

[0.43351057 0.19019227 0.5519552  0.40025288 0.4754011  0.51240814
 1.400183   1.8082656  0.71301794 0.6473072  0.821355   0.59074533
 0.6677656  0.26083875 0.20336185 0.66822714 0.7876549  0.2610022
 0.19150873 0.23388776 0.6272101  0.7314052  0.28481585 0.48324504
 0.260913   0.5361564  0.36507386 1.088813   0.45339772 0.5846097
 0.52401435 0.48974162 0.1603501  0.17993367 0.80340844 1.0471374
 0.25996393 0.5765119  0.45536062 0.3493029  1.4058895  0.33821407
 0.7151631  0.6379416  0.4921908  0.7319876  0.550202   0.5337183
 0.3621001  0.31814003 1.0573618  0.58011353 0.18870063 1.0902718
 0.5846097  0.60344195 0.31467885 0.5989495  0.19060938 0.19005838
 1.7984968  0.624896   0.347758   0.8287908  0.82846564 0.3750564
 0.21704744 0.20179851]
[0.42, 0.23, 0.54, 0.53, 0.44, 0.49, 1.39, 1.82, 0.77, 0.66, 0.8, 0.61, 0.68, 0.26, 0.21, 0.64, 0.85, 0.26, 0.17, 0.24, 0.61, 0.77, 0.29, 0.45, 0.24, 0.53, 0.36, 1.04, 0.44, 0.57, 0.55, 0.47, 0.18, 0.2, 0.76, 1.04, 0.24, 0.59, 0.45, 0.33, 1.41, 0.33, 0.72, 0.63, 0.49, 0.72, 0.56, 0.51, 0.35, 0.31, 1.1, 0.55, 0.15, 1.17, 0.66, 0.59, 0.29, 0.56, 0.16, 0.21, 1.88, 0.66, 0.36, 0.62, 0.83, 0.37, 0.21, 0.21]

In [129]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def regression_report(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    

    print("--- Regression Model Report ---")
    print(f"MAE (평균 절대 오차)  : {mae:.4f}")
    print(f"RMSE (평균 제곱근 오차): {rmse:.4f}")
    print(f"R2 Score (결정 계수)  : {r2:.4f}")
    print(f"MAPE (평균 절대 백분율 오차): {mape:.2f}%")
    print("-------------------------------")

# 사용 예시
regression_report(y_test, y_pred)

--- Regression Model Report ---
MAE (평균 절대 오차)  : 0.0260
RMSE (평균 제곱근 오차): 0.0410
R2 Score (결정 계수)  : 0.9869
MAPE (평균 절대 백분율 오차): 5.53%
-------------------------------

In [130]:
X_train

,연도_num,basis_대출잔액별,basis_매출액별,basis_사업기간별,basis_산업분류별,basis_성별,basis_연령별,cat_100천만원 이상,cat_10~15천만원 미만,cat_10년 이상,...,cat_부동산업,"cat_사업시설 관리, 사업지원 및 임대 서비스업",cat_숙박 및 음식점업,cat_여자,"cat_예술, 스포츠 및 여가관련 서비스업",cat_운수 및 창고업,"cat_전문, 과학 및 기술 서비스업",cat_정보통신업,cat_제조업,"cat_협회 및 단체, 수리 및 기타 개인서비스업"
43,2018,False,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
192,2021,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
209,2021,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
326,2024,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
330,2024,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,2019,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
112,2019,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
329,2024,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
258,2023,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
120,2019,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [131]:
y_pred = model.predict(X_train)
print(y_pred)
print(list(y_test))

[0.35963848 0.34970814 0.1507386  0.9496752  1.1070799  0.93534124
 1.1760402  0.42225206 1.0298362  0.49104178 0.54252017 0.42767966
 0.21816447 1.8323646  0.26525673 0.33100337 0.4596758  0.47943553
 0.22306706 0.3018558  0.8397599  0.93534124 0.8237052  0.33068278
 0.17845213 0.43608978 0.6163194  0.43557993 0.6045785  0.7151631
 0.30925635 0.6005476  1.4038893  0.785171   0.40436298 0.7955526
 0.3979069  0.62761676 0.63114893 1.6836277  0.63948685 0.78301364
 0.59976405 0.31258723 0.40311724 0.2238856  0.15413462 0.6784519
 1.2344342  1.6773238  0.9481269  0.6149789  0.25861964 0.50759566
 0.7013289  0.97975826 0.6972483  0.26060107 0.37190583 0.27157018
 0.22634701 0.8222209  0.5126352  1.4009036  0.49933234 0.22213991
 0.3000626  0.49485132 0.74455327 0.49757868 0.28357404 0.27838007
 0.40256974 0.2899863  0.4910402  0.6381388  0.63456607 0.9494428
 0.5091849  0.28162682 1.472391   0.28710437 0.5480074  0.5358683
 0.12731041 0.31005818 0.40233144 0.2255847  0.48324504 1.0852406
 0.7294971  0.9485527  0.28353134 0.25735107 0.1937294  0.6700852
 0.58382595 0.37974477 1.2297362  0.49188215 0.35529    0.518548
 0.2306907  0.35800317 0.41238582 0.84752196 1.0657037  1.8522625
 0.46134192 0.30303475 0.43068463 0.8191276  0.16847828 0.32403046
 0.3237813  0.69683915 0.27549812 0.22228152 0.59462804 0.3613144
 0.7296065  0.5320588  0.54776263 0.20837887 0.5540238  0.5607492
 0.6849147  0.7803214  0.5601433  0.15687203 0.41100058 0.5301542
 0.7443266  0.11933305 1.4571456  0.19101872 0.23450552 0.25663304
 1.0227957  0.33313367 0.5808003  0.6368529  0.87009376 0.37691882
 0.63837546 0.25273052 0.5953152  1.076744   0.5495754  0.27935055
 0.55004364 1.426168   0.31124294 0.93010986 0.7877737  1.8009856
 1.0062991  0.38232398 0.15916339 1.0486441  1.4413005  0.38666263
 0.10772685 0.3829566  1.0030488  0.96450466 0.56437224 0.3250725
 0.86246705 0.7761675  0.9259925  1.2374808  1.3314872  0.41037038
 1.2282636  0.29069835 0.95825773 0.7279488  1.1971418  0.9647314
 0.55004364 0.4576248  0.18286861 0.34982032 0.86248183 0.5650315
 0.31423795 0.6917738  1.1016942  0.5242414  0.96877575 0.6265851
 0.16234484 0.24923252 0.5459565  0.31902254 0.57149035 1.0568143
 0.3853168  0.21998511 0.56525844 0.4878242  0.6033933  0.49567425
 0.3878776  1.0418969  0.98273313 0.20949535 1.008086   0.5711713
 0.8396794  0.58984166 0.6196036  0.30423737 0.44025087 0.43955985
 0.38386887 0.6932526  0.50562435 0.9142323  0.41883177 0.3653282
 0.638008   0.48115087 0.22710873 0.53155255 0.65806335 0.34880394
 0.34462416 0.4942417  0.4494509  0.35049385 1.1852235  0.3423528
 0.8839119  0.3439677  0.6676021  0.584373   0.8677571  0.9382576
 0.5462343  0.61560386 0.17126237 0.44556656 0.63837546 0.35526147
 0.8883355  0.90563446 0.38265684 1.0094603  0.4817304  0.7121761
 0.5730255  0.33716512 1.0880687  0.24611181 0.58309656 0.88385516
 0.13891663 0.49485132 0.5358683  0.27490488 0.26967138 0.701073
 0.30649632 1.2602968  0.44036892 0.7667837 ]
[0.42, 0.23, 0.54, 0.53, 0.44, 0.49, 1.39, 1.82, 0.77, 0.66, 0.8, 0.61, 0.68, 0.26, 0.21, 0.64, 0.85, 0.26, 0.17, 0.24, 0.61, 0.77, 0.29, 0.45, 0.24, 0.53, 0.36, 1.04, 0.44, 0.57, 0.55, 0.47, 0.18, 0.2, 0.76, 1.04, 0.24, 0.59, 0.45, 0.33, 1.41, 0.33, 0.72, 0.63, 0.49, 0.72, 0.56, 0.51, 0.35, 0.31, 1.1, 0.55, 0.15, 1.17, 0.66, 0.59, 0.29, 0.56, 0.16, 0.21, 1.88, 0.66, 0.36, 0.62, 0.83, 0.37, 0.21, 0.21]

In [132]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def regression_report(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    

    print("--- Regression Model Report ---")
    print(f"MAE (평균 절대 오차)  : {mae:.4f}")
    print(f"RMSE (평균 제곱근 오차): {rmse:.4f}")
    print(f"R2 Score (결정 계수)  : {r2:.4f}")
    print(f"MAPE (평균 절대 백분율 오차): {mape:.2f}%")
    print("-------------------------------")

# 사용 예시
regression_report(y_train, y_pred)

--- Regression Model Report ---
MAE (평균 절대 오차)  : 0.0296
RMSE (평균 제곱근 오차): 0.0517
R2 Score (결정 계수)  : 0.9795
MAPE (평균 절대 백분율 오차): 5.40%
-------------------------------

In [133]:
df_final

,target_연체율,연도_num,basis_대출잔액별,basis_매출액별,basis_사업기간별,basis_산업분류별,basis_성별,basis_연령별,cat_100천만원 이상,cat_10~15천만원 미만,...,cat_부동산업,"cat_사업시설 관리, 사업지원 및 임대 서비스업",cat_숙박 및 음식점업,cat_여자,"cat_예술, 스포츠 및 여가관련 서비스업",cat_운수 및 창고업,"cat_전문, 과학 및 기술 서비스업",cat_정보통신업,cat_제조업,"cat_협회 및 단체, 수리 및 기타 개인서비스업"
0,0.60,2017,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,0.33,2017,False,False,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2,0.95,2017,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
3,0.59,2017,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,0.55,2017,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,1.16,2024,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
332,1.14,2024,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
333,0.82,2024,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
334,0.54,2024,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
335,0.54,2024,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [134]:
X_train = df_final.iloc[df_final["연도_num"] != 2024,1:]
X_test = df_final.iloc[df_final["연도_num"] == 2024,1:]
y_train = df_final.iloc[df_final["연도_num"] != 2024,0]
y_test = df_final.iloc[df_final["연도_num"] == 2024,0]

In [135]:
y_pred = model.predict(X_test)
print(y_pred)
print(list(y_test))

[1.0094603  0.7013289  1.6773238  1.0486441  0.9481269  0.8191276
 0.65806335 0.6196036  1.8009856  0.9647314  1.0657037  1.0902718
 0.7803214  0.88385516 1.2282636  0.43955985 1.0471374  1.2344342
 0.7319876  0.28353134 0.93534124 0.93534124 0.6368529  1.4413005
 0.6379416  0.54252017 0.50759566 0.4754011  0.3979069  0.33068278
 0.22710873 0.96450466 0.9496752  0.5730255  1.426168   1.2602968
 1.1070799  1.1016942  1.0418969  0.8397599  0.58984166 0.59462804]
[1.04, 0.66, 1.75, 1.11, 1.04, 0.79, 0.61, 0.58, 1.95, 0.95, 1.11, 1.17, 0.75, 0.88, 1.25, 0.44, 1.04, 1.67, 0.72, 0.23, 1.07, 0.96, 0.56, 1.52, 0.63, 0.56, 0.5, 0.44, 0.33, 0.27, 0.22, 1.06, 1.06, 0.52, 1.39, 1.28, 1.17, 1.16, 1.14, 0.82, 0.54, 0.54]

In [136]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def regression_report(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    

    print("--- Regression Model Report ---")
    print(f"MAE (평균 절대 오차)  : {mae:.4f}")
    print(f"RMSE (평균 제곱근 오차): {rmse:.4f}")
    print(f"R2 Score (결정 계수)  : {r2:.4f}")
    print(f"MAPE (평균 절대 백분율 오차): {mape:.2f}%")
    print("-------------------------------")

# 사용 예시
regression_report(y_test, y_pred)

--- Regression Model Report ---
MAE (평균 절대 오차)  : 0.0582
RMSE (평균 제곱근 오차): 0.0899
R2 Score (결정 계수)  : 0.9519
MAPE (평균 절대 백분율 오차): 6.97%
-------------------------------

In [137]:
y_pred = model.predict(X_train)
print(y_pred)
print(list(y_test))

[0.59976405 0.3250725  0.9485527  0.60344195 0.5462343  0.4576248
 0.3439677  0.3423528  1.0062991  0.5607492  0.5540238  0.69683915
 0.3493029  0.41883177 0.8396794  0.28481585 0.7876549  1.0227957
 0.44025087 0.2306907  0.55004364 0.55004364 0.62761676 0.8839119
 0.41100058 0.347758   0.28357404 0.26967138 0.21816447 0.15916339
 0.15413462 0.58382595 0.5765119  0.31423795 1.8082656  0.9382576
 0.6784519  0.53155255 0.4596758  0.31005818 0.22634701 0.19101872
 0.63948685 0.35963848 1.088813   0.638008   0.5808003  0.4921908
 0.37974477 0.37691882 1.1852235  0.5953152  0.6473072  0.7314052
 0.38386887 0.45339772 0.8883355  0.30303475 0.8222209  1.0573618
 0.45536062 0.26525673 0.5846097  0.5846097  0.56437224 0.9259925
 0.44556656 0.38232398 0.31814003 0.30423737 0.25273052 0.1937294
 0.18870063 0.63114893 0.6163194  0.34880394 1.7984968  1.0030488
 0.71301794 0.584373   0.4942417  0.34462416 0.260913   0.2255847
 0.6932526  0.40436298 1.1760402  0.6917738  0.63456607 0.5459565
 0.43351057 0.43068463 1.4009036  0.6677656  0.701073   0.785171
 0.4878242  0.50562435 0.9142323  0.35526147 0.86246705 1.0852406
 0.48974162 0.31902254 0.63837546 0.63837546 0.58011353 0.97975826
 0.49933234 0.43608978 0.37190583 0.35800317 0.30649632 0.25735107
 0.19150873 0.6849147  0.6700852  0.40256974 1.8522625  1.0568143
 0.7667837  0.6381388  0.5480074  0.3878776  0.31467885 0.27935055
 0.59074533 0.3018558  1.0298362  0.5711713  0.5320588  0.42767966
 0.33100337 0.30925635 1.4058895  0.56525844 0.6045785  0.6676021
 0.3853168  0.40311724 0.8287908  0.26060107 0.6972483  0.98273313
 0.31258723 0.2238856  0.5358683  0.5358683  0.43557993 0.821355
 0.40233144 0.3237813  0.27490488 0.2610022  0.20949535 0.1603501
 0.17993367 0.5650315  0.550202   0.3000626  1.8323646  0.95825773
 0.66822714 0.5337183  0.4494509  0.31124294 0.22306706 0.20336185
 0.5361564  0.24923252 0.9494428  0.518548   0.47943553 0.3750564
 0.27838007 0.25663304 1.4038893  0.5126352  0.5519552  0.6149789
 0.33821407 0.35049385 0.7761675  0.19019227 0.57149035 0.93010986
 0.25996393 0.17126237 0.48324504 0.48324504 0.3829566  0.7121761
 0.34970814 0.27549812 0.22228152 0.20837887 0.15687203 0.10772685
 0.12731041 0.51240814 0.49757868 0.23450552 1.472391   0.90563446
 0.61560386 0.4910402  0.42225206 0.25861964 0.17845213 0.1507386
 0.54776263 0.26083875 1.076744   0.5301542  0.49104178 0.38666263
 0.2899863  0.29069835 1.400183   0.5242414  0.6033933  0.6265851
 0.34982032 0.3621001  0.7877737  0.20179851 0.58309656 0.96877575
 0.27157018 0.18286861 0.49485132 0.49485132 0.35529    0.7296065
 0.3613144  0.28710437 0.23388776 0.21998511 0.16847828 0.11933305
 0.13891663 0.52401435 0.5091849  0.24611181 1.3314872  0.8677571
 0.6272101  0.5495754  0.46134192 0.32403046 0.19005838 0.16234484
 0.78301364 0.48115087 1.4571456  0.82846564 0.7279488  0.5989495
 0.44036892 0.41238582 1.6836277  0.74455327 0.8237052  0.87009376
 0.5601433  0.624896   1.008086   0.33716512 0.80340844 1.1971418
 0.49188215 0.21704744 0.7151631  0.7151631  0.4817304  1.2374808
 0.49567425 0.40025288 0.3653282  0.33313367 0.28162682 0.22213991
 0.19060938 0.7443266  0.7294971  0.36507386 1.2297362  1.0880687
 0.84752196 0.86248183 0.7955526  0.6005476  0.41037038 0.38265684]
[1.04, 0.66, 1.75, 1.11, 1.04, 0.79, 0.61, 0.58, 1.95, 0.95, 1.11, 1.17, 0.75, 0.88, 1.25, 0.44, 1.04, 1.67, 0.72, 0.23, 1.07, 0.96, 0.56, 1.52, 0.63, 0.56, 0.5, 0.44, 0.33, 0.27, 0.22, 1.06, 1.06, 0.52, 1.39, 1.28, 1.17, 1.16, 1.14, 0.82, 0.54, 0.54]

In [138]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def regression_report(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    

    print("--- Regression Model Report ---")
    print(f"MAE (평균 절대 오차)  : {mae:.4f}")
    print(f"RMSE (평균 제곱근 오차): {rmse:.4f}")
    print(f"R2 Score (결정 계수)  : {r2:.4f}")
    print(f"MAPE (평균 절대 백분율 오차): {mape:.2f}%")
    print("-------------------------------")

# 사용 예시
regression_report(y_train, y_pred)

--- Regression Model Report ---
MAE (평균 절대 오차)  : 0.0247
RMSE (평균 제곱근 오차): 0.0409
R2 Score (결정 계수)  : 0.9849
MAPE (평균 절대 백분율 오차): 5.21%
-------------------------------

In [118]:
df_final.head(1).to_csv("결과.csv", encoding='cp949')

In [207]:
df_test = pd.read_csv("결과.csv", encoding='cp949')
df_test

,연도_num,basis_대출잔액별,basis_매출액별,basis_사업기간별,basis_산업분류별,basis_성별,basis_연령별,cat_100천만원 이상,cat_10~15천만원 미만,cat_10년 이상,...,cat_부동산업,"cat_사업시설 관리, 사업지원 및 임대 서비스업",cat_숙박 및 음식점업,cat_여자,"cat_예술, 스포츠 및 여가관련 서비스업",cat_운수 및 창고업,"cat_전문, 과학 및 기술 서비스업",cat_정보통신업,cat_제조업,"cat_협회 및 단체, 수리 및 기타 개인서비스업"
0,2026,True,True,True,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2027,True,True,True,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,2033,True,True,True,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,2040,True,True,True,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,2017,True,True,True,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,2010,True,True,True,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,2005,True,True,True,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [208]:
model.predict(df_test)

array([0.706827  , 0.706827  , 0.706827  , 0.706827  , 0.17666766,
       0.17666766, 0.17666766], dtype=float32)

In [138]:
df_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   연도_num                       7 non-null      int64
 1   basis_대출잔액별                  7 non-null      bool
 2   basis_매출액별                   7 non-null      bool
 3   basis_사업기간별                  7 non-null      bool
 4   basis_산업분류별                  7 non-null      bool
 5   basis_성별                     7 non-null      bool
 6   basis_연령별                    7 non-null      bool
 7   cat_100천만원 이상                7 non-null      bool
 8   cat_10~15천만원 미만              7 non-null      bool
 9   cat_10년 이상                   7 non-null      bool
 10  cat_15~30천만원 미만              7 non-null      bool
 11  cat_1~2억원 미만                 7 non-null      bool
 12  cat_1~3천만원 미만                7 non-null      bool
 13  cat_1천만원 미만                  7 non-null      bool
 14  cat_29세 이하                   7 non-null      bool
 15  cat_2~3억원 미만                 7 non-null      bool
 16  cat_30~39세                   7 non-null      bool
 17  cat_30~50천만원 미만              7 non-null      bool
 18  cat_3~10년 미만                 7 non-null      bool
 19  cat_3~5천만원 미만                7 non-null      bool
 20  cat_3년 미만                    7 non-null      bool
 21  cat_3억원 이상                   7 non-null      bool
 22  cat_3천만원 미만                  7 non-null      bool
 23  cat_40~49세                   7 non-null      bool
 24  cat_50~100천만원 미만             7 non-null      bool
 25  cat_50~59세                   7 non-null      bool
 26  cat_5~10천만원 미만               7 non-null      bool
 27  cat_5~7천만원 미만                7 non-null      bool
 28  cat_60~69세                   7 non-null      bool
 29  cat_70세 이상                   7 non-null      bool
 30  cat_7천만~1억원 미만               7 non-null      bool
 31  cat_건설업                      7 non-null      bool
 32  cat_교육 서비스업                  7 non-null      bool
 33  cat_기타                       7 non-null      bool
 34  cat_남자                       7 non-null      bool
 35  cat_농업, 임업 및 어업              7 non-null      bool
 36  cat_도매 및 소매업                 7 non-null      bool
 37  cat_보건업 및 사회복지 서비스업          7 non-null      bool
 38  cat_부동산업                     7 non-null      bool
 39  cat_사업시설 관리, 사업지원 및 임대 서비스업  7 non-null      bool
 40  cat_숙박 및 음식점업                7 non-null      bool
 41  cat_여자                       7 non-null      bool
 42  cat_예술, 스포츠 및 여가관련 서비스업      7 non-null      bool
 43  cat_운수 및 창고업                 7 non-null      bool
 44  cat_전문, 과학 및 기술 서비스업         7 non-null      bool
 45  cat_정보통신업                    7 non-null      bool
 46  cat_제조업                      7 non-null      bool
 47  cat_협회 및 단체, 수리 및 기타 개인서비스업  7 non-null      bool
dtypes: bool(47), int64(1)
memory usage: 517.0 bytes

In [141]:
X_train = df_final.iloc[df_final["연도_num"] != 2024,1:]
X_test = df_final.iloc[df_final["연도_num"] == 2024,1:]
y_train = df_final.iloc[df_final["연도_num"] != 2024,0]
y_test = df_final.iloc[df_final["연도_num"] == 2024,0]

In [147]:
y_pred = model.predict(X_test)
print(y_pred)
print(list(y_test))

[0.6148225  0.33308113 0.9718624  0.6005597  0.54845    0.46015787
 0.32840428 0.3318375  1.0662849  0.54903156 0.579581   0.6723559
 0.35185713 0.4027023  0.80839807 0.31019673 0.83296144 1.0406986
 0.43269342 0.2148889  0.54903156 0.58131224 0.5935433  0.89677656
 0.41323873 0.34443694 0.2808347  0.26484826 0.20582448 0.1357694
 0.13053516 0.5966317  0.5692119  0.29133752 1.8366497  0.97490275
 0.68598515 0.5388744  0.46982223 0.28800243 0.21076296 0.19015643]
[1.04, 0.66, 1.75, 1.11, 1.04, 0.79, 0.61, 0.58, 1.95, 0.95, 1.11, 1.17, 0.75, 0.88, 1.25, 0.44, 1.04, 1.67, 0.72, 0.23, 1.07, 0.96, 0.56, 1.52, 0.63, 0.56, 0.5, 0.44, 0.33, 0.27, 0.22, 1.06, 1.06, 0.52, 1.39, 1.28, 1.17, 1.16, 1.14, 0.82, 0.54, 0.54]

In [57]:
model = XGBRegressor(learning_rate= 0.2, max_depth=3, n_estimators=70)
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.2, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=70,
             n_jobs=None, num_parallel_tree=None, ...)

In [151]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def regression_report(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    

    print("--- Regression Model Report ---")
    print(f"MAE (평균 절대 오차)  : {mae:.4f}")
    print(f"RMSE (평균 제곱근 오차): {rmse:.4f}")
    print(f"R2 Score (결정 계수)  : {r2:.4f}")
    print(f"MAPE (평균 절대 백분율 오차): {mape:.2f}%")
    print("-------------------------------")

# 사용 예시
regression_report(y_test, y_pred)

--- Regression Model Report ---
MAE (평균 절대 오차)  : 0.3795
RMSE (평균 제곱근 오차): 0.4264
R2 Score (결정 계수)  : -0.0827
MAPE (평균 절대 백분율 오차): 42.07%
-------------------------------

In [152]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold

xgb_model = XGBRegressor()
cv = KFold(n_splits=5, random_state=639, shuffle=True)
parameters = {'n_estimators' : [50,60,70,80,90,100], 'learning_rate':[0.1,0.2,0.3,0.4],
             'max_depth':[3,4,5,6,7]}
model = GridSearchCV(estimator = xgb_model,
                     param_grid = parameters,
                     cv = cv, verbose = 1,
                     n_jobs = 1, refit = True)
model.fit(X_train, y_train)

Fitting 5 folds for each of 120 candidates, totalling 600 fits

GridSearchCV(cv=KFold(n_splits=5, random_state=639, shuffle=True),
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=None, grow_policy=None,
                                    imp...
                                    max_cat_threshold=None,
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=1,
             param_grid={'learning_rate': [0.1, 0.2, 0.3, 0.4],
                         'max_depth': [3, 4, 5, 6, 7],
                         'n_estimators': [50, 60, 70, 80, 90, 100]},
             verbose=1)

In [153]:
print("Best Estimator:\n", model.best_estimator_)
print("Best Params:\n", model.best_params_)
print("Best Score:\n", model.best_score_)

Best Estimator:
 XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.4, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)
Best Params:
 {'learning_rate': 0.4, 'max_depth': 5, 'n_estimators': 100}
Best Score:
 0.9486571120199947

In [154]:
model = XGBRegressor(learning_rate=0.4, max_depth=5, n_estimators=100)
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.4, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [155]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def regression_report(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    

    print("--- Regression Model Report ---")
    print(f"MAE (평균 절대 오차)  : {mae:.4f}")
    print(f"RMSE (평균 제곱근 오차): {rmse:.4f}")
    print(f"R2 Score (결정 계수)  : {r2:.4f}")
    print(f"MAPE (평균 절대 백분율 오차): {mape:.2f}%")
    print("-------------------------------")

# 사용 예시
regression_report(y_test, y_pred)

--- Regression Model Report ---
MAE (평균 절대 오차)  : 0.3795
RMSE (평균 제곱근 오차): 0.4264
R2 Score (결정 계수)  : -0.0827
MAPE (평균 절대 백분율 오차): 42.07%
-------------------------------

In [35]:
import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from xgboost import plot_importance, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
import scikitplot as skplt
import re


def regression_report(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    

    print("--- Regression Model Report ---")
    print(f"MAE (평균 절대 오차)  : {mae:.4f}")
    print(f"RMSE (평균 제곱근 오차): {rmse:.4f}")
    print(f"R2 Score (결정 계수)  : {r2:.4f}")
    print(f"MAPE (평균 절대 백분율 오차): {mape:.2f}%")
    print("-------------------------------")

# 1. 데이터 로드
df = pd.read_csv('차주수기준_은행금융기관별_전체연도_정리_금리추가.csv')

# 2. 전처리 함수
def preprocess_for_xgb(df):
    # (1) 연도 컬럼 찾기 (숫자 4자리가 포함된 컬럼 추출)
    year_cols = [col for col in df.columns if re.search(r'\d{4}', col)]
    
    # (2) Wide to Long 변환 (Melting)
    # 가로로 나열된 연도 데이터를 '연도'라는 하나의 변수로 통합합니다.
    df_long = df.melt(
        id_vars=['기준', '구분'], 
        value_vars=year_cols, 
        var_name='연도_raw', 
        value_name='target_연체율'
    )
    
    # (3) 연도 숫자 정제 ('2024 p)' -> 2024)
    df_long['연도_num'] = df_long['연도_raw'].str.extract(r'(\d{4})').astype(int)
    
    # (4) 금리 데이터 매핑
    # 데이터 내 '기준'이 '금리'인 행을 찾아 연도별 금리 테이블을 만듭니다.
    interest_map = df_long[df_long['기준'] == '금리'][['연도_num', 'target_연체율']]
    interest_map = interest_map.rename(columns={'target_연체율': '기준금리'})
    
    # (5) 금리 행 제외 및 금리 컬럼 결합
    # 금리 자체는 예측 대상이 아니므로 학습 데이터에서 분리하여 컬럼으로 붙입니다.
    df_data = df_long[df_long['기준'] != '금리'].copy()
    df_final = pd.merge(df_data, interest_map, on='연도_num', how='left')
    
    # (6) 범주형 데이터 처리 (One-Hot Encoding)
    # XGBoost가 이해할 수 있도록 '기준'과 '구분'을 수치형(0, 1)으로 변환합니다.
    df_final = pd.get_dummies(df_final, columns=['기준', '구분'], prefix=['basis', 'cat'])
    
    # 불필요한 원본 컬럼 제거
    df_final = df_final.drop(columns=['연도_raw'])
    
    return df_final

# 3. 전처리 실행
df_final = preprocess_for_xgb(df)

# 결과 확인
X_train = df_final.iloc[(df_final["연도_num"] != 2024) & (df_final["연도_num"] != 2023) & (df_final["연도_num"] != 2022),1:]
X_test = df_final.iloc[(df_final["연도_num"] == 2024) | (df_final["연도_num"] == 2023) | (df_final["연도_num"] == 2022),1:]
y_train = df_final.iloc[(df_final["연도_num"] != 2024) & (df_final["연도_num"] != 2023) & (df_final["연도_num"] != 2022),0]
y_test = df_final.iloc[(df_final["연도_num"] == 2024) | (df_final["연도_num"] == 2023) | (df_final["연도_num"] == 2022),0]

model = XGBRegressor(learning_rate = 0.3, max_depth = 4, n_estimators = 100)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
regression_report(y_test, y_pred)
X_pred = model.predict(X_train)
regression_report(y_train, X_pred)

--- Regression Model Report ---
MAE (평균 절대 오차)  : 0.2137
RMSE (평균 제곱근 오차): 0.2967
R2 Score (결정 계수)  : 0.4557
MAPE (평균 절대 백분율 오차): 28.73%
-------------------------------
--- Regression Model Report ---
MAE (평균 절대 오차)  : 0.0125
RMSE (평균 제곱근 오차): 0.0190
R2 Score (결정 계수)  : 0.9970
MAPE (평균 절대 백분율 오차): 4.07%
-------------------------------

In [39]:
import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import re

def regression_report(y_true, y_pred, title="Model Report"):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / (y_true + 1e-10))) * 100 # 0 나누기 방지

    print(f"--- {title} ---")
    print(f"MAE (평균 절대 오차)  : {mae:.4f}")
    print(f"RMSE (평균 제곱근 오차): {rmse:.4f}")
    print(f"R2 Score (결정 계수)  : {r2:.4f}")
    print(f"MAPE (평균 절대 백분율 오차): {mape:.2f}%")
    print("-------------------------------")

# 1. 데이터 로드
file_name = '차주수기준_은행금융기관별_전체연도_정리_금리추가.csv'
df = pd.read_csv(file_name)

# 2. 전처리 함수 수정
def preprocess_for_xgb(df):
    # (1) 연도 컬럼 추출
    year_cols = [col for col in df.columns if re.search(r'\d{4}', col)]
    
    # (2) Wide to Long 변환
    df_long = df.melt(
        id_vars=['기준', '구분'], 
        value_vars=year_cols, 
        var_name='연도_raw', 
        value_name='target_연체율'
    )
    
    # (3) 연도 숫자 정제
    df_long['연도_num'] = df_long['연도_raw'].str.extract(r'(\d{4})').astype(int)
    
    # (4) 금리 데이터 및 직전 연도 금리(Lag) 피처 생성
    interest_map = df_long[df_long['기준'] == '금리'][['연도_num', 'target_연체율']]
    interest_map = interest_map.rename(columns={'target_연체율': '기준금리'}).drop_duplicates()
    
    # 직전 연도 금리 생성 (시계열 분석의 핵심)
    interest_map = interest_map.sort_values('연도_num')
    interest_map['직전연도금리'] = interest_map['기준금리'].shift(1)
    # 금리 변동폭 생성
    interest_map['금리변동폭'] = interest_map['기준금리'] - interest_map['직전연도금리']
    
    # (5) 금리 행 제외 및 피처 결합
    df_data = df_long[df_long['기준'] != '금리'].copy()
    df_final = pd.merge(df_data, interest_map, on='연도_num', how='left')
    
    # 결측치 처리 (첫 해인 2017년은 직전 금리가 없으므로 0 혹은 평균값 채움)

    df_final['금리변동폭'] = df_final['금리변동폭'].fillna(0)
    
    # (6) 범주형 데이터 처리 (One-Hot Encoding)
    df_final = pd.get_dummies(df_final, columns=['기준', '구분'], prefix=['basis', 'cat'])
    
    # (7) 불필요한 컬럼 제거
    df_final = df_final.drop(columns=['연도_raw'])
    
    return df_final

# 3. 전처리 실행
df_processed = preprocess_for_xgb(df)

# 4. 데이터 분할 (2022~2024를 테스트셋으로 설정)
train_mask = ~df_processed['연도_num'].isin([2022, 2023, 2024])
test_mask = df_processed['연도_num'].isin([2022, 2023, 2024])

# 타겟과 피처 분리
y = df_processed['target_연체율']
X = df_processed.drop(columns=['target_연체율'])

X_train, X_test = X[train_mask], X[test_mask]
y_train, y_test = y[train_mask], y[test_mask]

# 5. 모델 설정 및 학습 (과적합 방지를 위해 파라미터 보수적 조정)
model = XGBRegressor(
    learning_rate=0.05, 
    max_depth=3, 
    n_estimators=200,
    reg_lambda=1,
    random_state=42
)
model.fit(X_train, y_train)

# 6. 결과 리포트
y_test_pred = model.predict(X_test)
regression_report(y_test, y_test_pred, title="Test Set Performance (2022-2024)")

y_train_pred = model.predict(X_train)
regression_report(y_train, y_train_pred, title="Train Set Performance")

--- Test Set Performance (2022-2024) ---
MAE (평균 절대 오차)  : 0.2176
RMSE (평균 제곱근 오차): 0.3127
R2 Score (결정 계수)  : 0.3952
MAPE (평균 절대 백분율 오차): 30.43%
-------------------------------
--- Train Set Performance ---
MAE (평균 절대 오차)  : 0.0856
RMSE (평균 제곱근 오차): 0.0988
R2 Score (결정 계수)  : 0.9196
MAPE (평균 절대 백분율 오차): 22.12%
-------------------------------

In [36]:
df_final

,target_연체율,연도_num,기준금리,basis_금리변동폭,basis_대출잔액별,basis_매출액별,basis_사업기간별,basis_산업분류별,basis_성별,basis_연령별,...,"cat_사업시설 관리, 사업지원 및 임대 서비스업",cat_숙박 및 음식점업,cat_여자,"cat_예술, 스포츠 및 여가관련 서비스업",cat_운수 및 창고업,"cat_전문, 과학 및 기술 서비스업",cat_정보통신업,cat_제조업,cat_직전연도,"cat_협회 및 단체, 수리 및 기타 개인서비스업"
0,0.60,2017,3.49,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1,0.33,2017,3.49,False,False,False,False,False,True,False,...,False,False,True,False,False,False,False,False,False,False
2,0.95,2017,3.49,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,0.59,2017,3.49,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,0.55,2017,3.49,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,1.14,2024,4.85,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
340,0.82,2024,4.85,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
341,0.54,2024,4.85,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
342,0.54,2024,4.85,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
343,-0.43,2024,4.85,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [26]:
xgb_model = XGBRegressor()
cv = KFold(n_splits=5, random_state=639, shuffle=True)
parameters = {'n_estimators' : [50,60,70,80,90,100], 'learning_rate':[0.1,0.2,0.3,0.4],
             'max_depth':[3,4,5,6,7]}
model = GridSearchCV(estimator = xgb_model,
                     param_grid = parameters,
                     cv = cv, verbose = 1,
                     n_jobs = 1, refit = True)
model.fit(X_train, y_train)

Fitting 5 folds for each of 120 candidates, totalling 600 fits

GridSearchCV(cv=KFold(n_splits=5, random_state=639, shuffle=True),
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=None, grow_policy=None,
                                    imp...
                                    max_cat_threshold=None,
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=1,
             param_grid={'learning_rate': [0.1, 0.2, 0.3, 0.4],
                         'max_depth': [3, 4, 5, 6, 7],
                         'n_estimators': [50, 60, 70, 80, 90, 100]},
             verbose=1)

In [27]:
print("Best Estimator:\n", model.best_estimator_)
print("Best Params:\n", model.best_params_)
print("Best Score:\n", model.best_score_)

Best Estimator:
 XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.4, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)
Best Params:
 {'learning_rate': 0.4, 'max_depth': 4, 'n_estimators': 100}
Best Score:
 0.9899815341994863

In [68]:
import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from xgboost import plot_importance, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
import scikitplot as skplt

def regression_report(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    

    print("--- Regression Model Report ---")
    print(f"MAE (평균 절대 오차)  : {mae:.4f}")
    print(f"RMSE (평균 제곱근 오차): {rmse:.4f}")
    print(f"R2 Score (결정 계수)  : {r2:.4f}")
    print(f"MAPE (평균 절대 백분율 오차): {mape:.2f}%")
    print("-------------------------------")

# 1. 데이터 로드
df = pd.read_csv('차주수기준_은행금융기관별_전체연도_정리.csv')

# 2. Wide to Long 변환 (Melting)
# 연도별로 나열된 피처를 '연도'라는 하나의 변수로 통합합니다.
year_cols = [col for col in df.columns if col not in ['기준', '구분']]
df_long = df.melt(id_vars=['기준', '구분'], value_vars=year_cols, 
                  var_name='연도', value_name='target_연체율')

# 3. 데이터 정제 (Cleaning)
# '2024 p)' 같은 텍스트 데이터에서 숫자만 추출하여 정수형으로 변환합니다.
df_long['연도_num'] = df_long['연도'].str.extract('(\d+)').astype(int)

# 4. 범주형 데이터 처리 (Encoding)
# '기준'과 '구분' 피처를 XGBoost가 이해할 수 있도록 수치 벡터로 변환합니다.
# 데이터의 카테고리 수가 적절하므로 One-Hot Encoding을 사용합니다.
df_final = pd.get_dummies(df_long, columns=['기준', '구분'], prefix=['basis', 'cat'])

# 학습에 사용하지 않을 원본 '연도' 컬럼 삭제
df_final = df_final.drop(columns=['연도'])

# 5. 최종 데이터 확인
df_final

X_train, X_test, y_train, y_test = train_test_split(df_final.iloc[:,1:], df_final.iloc[:,0], random_state=164, test_size=0.2)

model = XGBRegressor(learning_rate=0.4, max_depth=2, n_estimators=200)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
regression_report(y_test, y_pred)
X_pred = model.predict(X_train)
regression_report(y_train, X_pred)

--- Regression Model Report ---
MAE (평균 절대 오차)  : 0.0385
RMSE (평균 제곱근 오차): 0.0490
R2 Score (결정 계수)  : 0.9813
MAPE (평균 절대 백분율 오차): 10.31%
-------------------------------
--- Regression Model Report ---
MAE (평균 절대 오차)  : 0.0284
RMSE (평균 제곱근 오차): 0.0397
R2 Score (결정 계수)  : 0.9880
MAPE (평균 절대 백분율 오차): 6.38%
-------------------------------

In [61]:
xgb_model = XGBRegressor()
cv = KFold(n_splits=5, random_state=164, shuffle=True)
parameters = {'n_estimators' : [50,60,70,80,90,100], 'learning_rate':[0.1,0.2,0.3,0.4],
             'max_depth':[3,4,5,6,7]}
model = GridSearchCV(estimator = xgb_model,
                     param_grid = parameters,
                     cv = cv, verbose = 1,
                     n_jobs = 1, refit = True)
model.fit(X_train, y_train)

Fitting 5 folds for each of 120 candidates, totalling 600 fits

GridSearchCV(cv=KFold(n_splits=5, random_state=164, shuffle=True),
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=None, grow_policy=None,
                                    imp...
                                    max_cat_threshold=None,
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=1,
             param_grid={'learning_rate': [0.1, 0.2, 0.3, 0.4],
                         'max_depth': [3, 4, 5, 6, 7],
                         'n_estimators': [50, 60, 70, 80, 90, 100]},
             verbose=1)

In [62]:
print("Best Estimator:\n", model.best_estimator_)
print("Best Params:\n", model.best_params_)
print("Best Score:\n", model.best_score_)

Best Estimator:
 XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.4, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)
Best Params:
 {'learning_rate': 0.4, 'max_depth': 4, 'n_estimators': 100}
Best Score:
 0.9315282290652205

In [60]:
df_final.to_csv("모델학습용_데이터_전처리_결과.csv",encoding="cp949")

In [8]:
import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from xgboost import plot_importance, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
import scikitplot as skplt

def regression_report(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    

    print("--- Regression Model Report ---")
    print(f"MAE (평균 절대 오차)  : {mae:.4f}")
    print(f"RMSE (평균 제곱근 오차): {rmse:.4f}")
    print(f"R2 Score (결정 계수)  : {r2:.4f}")
    print(f"MAPE (평균 절대 백분율 오차): {mape:.2f}%")
    print("-------------------------------")

# 1. 데이터 로드
df = pd.read_csv('차주수기준_은행금융기관별_전체연도_정리.csv')

# 2. Wide to Long 변환 (Melting)
# 연도별로 나열된 피처를 '연도'라는 하나의 변수로 통합합니다.
year_cols = [col for col in df.columns if col not in ['기준', '구분']]
df_long = df.melt(id_vars=['기준', '구분'], value_vars=year_cols, 
                  var_name='연도', value_name='target_연체율')

# 3. 데이터 정제 (Cleaning)
# '2024 p)' 같은 텍스트 데이터에서 숫자만 추출하여 정수형으로 변환합니다.
df_long['연도_num'] = df_long['연도'].str.extract('(\d+)').astype(int)

# 4. 범주형 데이터 처리 (Encoding)
# '기준'과 '구분' 피처를 XGBoost가 이해할 수 있도록 수치 벡터로 변환합니다.
# 데이터의 카테고리 수가 적절하므로 One-Hot Encoding을 사용합니다.
df_final = pd.get_dummies(df_long, columns=['기준', '구분'], prefix=['basis', 'cat'])

# 학습에 사용하지 않을 원본 '연도' 컬럼 삭제
df_final = df_final.drop(columns=['연도'])

# 5. 최종 데이터 확인
df_final

X_train, X_test, y_train, y_test = train_test_split(df_final.iloc[:,1:], df_final.iloc[:,0], test_size=0.2)

model = XGBRegressor()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
regression_report(y_test, y_pred)

--- Regression Model Report ---
MAE (평균 절대 오차)  : 0.0709
RMSE (평균 제곱근 오차): 0.1464
R2 Score (결정 계수)  : 0.8570
MAPE (평균 절대 백분율 오차): 11.69%
-------------------------------