In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# 1번

In [2]:
# 타이타닉 데이터 로드
df = pd.read_csv('train.csv')

# 결측치 개수 출력
print(df[['Age','Embarked']].isna().sum())

# 결측치 처리 객체 생성
imp1 = SimpleImputer(missing_values=np.nan, strategy='mean')
imp2 = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

# 결측치 처리 후 저장
df['Age'] = imp1.fit_transform(df[['Age']]).ravel()
df['Embarked'] = imp2.fit_transform(df[['Embarked']]).ravel()

# 결측치 개수 출력
print(df[['Age','Embarked']].isna().sum())

Age         177
Embarked      2
dtype: int64
Age         0
Embarked    0
dtype: int64

# 2번

In [3]:
# 데이터 프레임 복사
df2 = df.copy()

# 레이블 인코더 객체 생성
le = LabelEncoder()

# 레이블 인코딩
sex = le.fit_transform(df2['Sex'])
embarked = le.fit_transform(df2['Embarked'])

# 기존 컬럼 삭제
df2 = df2.drop(['Sex', 'Embarked'],axis=1)

# 새로운 컬럼에 인코딩한 결과 저장
df2['Sex'] = sex
df2['Embarked'] = embarked

# 결과 출력
df2

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Sex,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",22.000000,1,0,A/5 21171,7.2500,NaN,1,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.000000,1,0,PC 17599,71.2833,C85,0,0
2,3,1,3,"Heikkinen, Miss. Laina",26.000000,0,0,STON/O2. 3101282,7.9250,NaN,0,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.000000,1,0,113803,53.1000,C123,0,2
4,5,0,3,"Allen, Mr. William Henry",35.000000,0,0,373450,8.0500,NaN,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.000000,0,0,211536,13.0000,NaN,1,2
887,888,1,1,"Graham, Miss. Margaret Edith",19.000000,0,0,112053,30.0000,B42,0,2
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",29.699118,1,2,W./C. 6607,23.4500,NaN,0,2
889,890,1,1,"Behr, Mr. Karl Howell",26.000000,0,0,111369,30.0000,C148,1,0
890,891,0,3,"Dooley, Mr. Patrick",32.000000,0,0,370376,7.7500,NaN,1,1

# 3번

In [4]:
# 데이터 프레임 복사
df3 = df.copy()

# 원핫 인코더 객체 생성
enc = OneHotEncoder()

# 적용할 대상
target = ['Sex', 'Embarked']

# 인코딩 결과
result = enc.fit_transform(df3[target])

# 새로운 컬럼 이름
col_names = enc.get_feature_names_out(target)

# 인코딩 결과를 데이터 프레임으로 변환
df_result = pd.DataFrame(result.toarray(), columns=col_names, index=df3.index)

# 기존 컬럼 삭제
df3 = df3.drop(columns=target)

# 인코딩 결과를 df3에 추가
df3 = pd.concat([df3, df_result], axis=1)

# 결과 출력
df3

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",22.000000,1,0,A/5 21171,7.2500,NaN,0.0,1.0,0.0,0.0,1.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.000000,1,0,PC 17599,71.2833,C85,1.0,0.0,1.0,0.0,0.0
2,3,1,3,"Heikkinen, Miss. Laina",26.000000,0,0,STON/O2. 3101282,7.9250,NaN,1.0,0.0,0.0,0.0,1.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.000000,1,0,113803,53.1000,C123,1.0,0.0,0.0,0.0,1.0
4,5,0,3,"Allen, Mr. William Henry",35.000000,0,0,373450,8.0500,NaN,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.000000,0,0,211536,13.0000,NaN,0.0,1.0,0.0,0.0,1.0
887,888,1,1,"Graham, Miss. Margaret Edith",19.000000,0,0,112053,30.0000,B42,1.0,0.0,0.0,0.0,1.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",29.699118,1,2,W./C. 6607,23.4500,NaN,1.0,0.0,0.0,0.0,1.0
889,890,1,1,"Behr, Mr. Karl Howell",26.000000,0,0,111369,30.0000,C148,0.0,1.0,1.0,0.0,0.0
890,891,0,3,"Dooley, Mr. Patrick",32.000000,0,0,370376,7.7500,NaN,0.0,1.0,0.0,1.0,0.0